
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 30 14:40:24 ART 2019
//----------------------------------------------------

package parserMiniJava;

/** CUP generated interface containing symbol constants. */
public interface symMiniJava {
  /* terminals */
  public static final int RPARENT = 4;
  public static final int WHILE = 13;
  public static final int INT = 9;
  public static final int LBRACE = 5;
  public static final int INTEGER = 14;
  public static final int EQUAL = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int IF = 11;
  public static final int ID = 15;
  public static final int ELSE = 12;
  public static final int error = 1;
  public static final int SEMICOLON = 7;
  public static final int RETURN = 10;
  public static final int LPARENT = 3;
  public static final int RBRACE = 6;
}

